Repository skdGT/feup-cal-project, pull requests merged in 2020-05, with the labels that each got.

#6 ihi
  Carro.cpp
  Carro.h
  Pessoa.cpp
  Pessoa.h
Labels: enhancement

#9 Documentação e Refactoring
  Carro.cpp
  Carro.h
  Pessoa.cpp
  Pessoa.h
  src/CMakeLists.txt
  src/Carro.cpp
  src/Local.cpp
  src/Pessoa.cpp
  src/include/Carro.h
  src/include/Local.h
  src/include/Pessoa.h
  src/lib/readme.md
  src/meetupRider.cpp
Labels: documentation, enhancement, refactoring

#11 Pre-Processamento de Dados | Caminho mais curto entre A e B
  CMakeLists.txt
  src/DataImporter.cpp
  src/DataProcessor.cpp
  src/Local.cpp
  src/include/DataImporter.h
  src/include/DataProcessor.h
  src/include/Graph.h
  src/include/Local.h
  src/include/MutablePriorityQueue.h
  src/meetupRider.cpp
Labels: enhancement

#12 Encontrar Caminhos entre A e B passando por N pontos
  src/DataImporter.cpp
  src/DataProcessor.cpp
  src/include/DataProcessor.h
  src/include/Graph.h
  src/meetupRider.cpp
Labels: enhancement

#13 CSV Reader
  .gitattributes
  CMakeLists.txt
  res/csvFiles/example.csv
  src/lib/CSVReader/CSVReader.cpp
  src/lib/CSVReader/CSVReader.h
  src/meetupRider.cpp
Labels: enhancement

#14 Documentation So Far
  CMakeLists.txt
  src/Carro.cpp
  src/DataImporter.cpp
  src/DataProcessor.cpp
  src/Local.cpp
  src/Person.cpp
  src/Pessoa.cpp
  src/Place.cpp
  src/Vehicle.cpp
  src/include/Carro.h
  src/include/DataImporter.h
  src/include/DataProcessor.h
  src/include/Local.h
  src/include/Person.h
  src/include/Pessoa.h
  src/include/Place.h
  src/include/Vehicle.h
  src/lib/CSVReader/CSVReader.h
  src/lib/GraphViewer/graphviewer.h
Labels: documentation, enhancement

#15 Lidar com Dados em CSV
  CMakeLists.txt
  res/csvFiles/cars.csv
  res/csvFiles/drivers.csv
  res/csvFiles/example.csv
  res/csvFiles/passengers.csv
  src/Application.cpp
  src/DataProcessor.cpp
  src/Person.cpp
  src/Vehicle.cpp
  src/include/Application.h
  src/include/DataProcessor.h
  src/include/Person.h
  src/include/Vehicle.h
  src/meetupRider.cpp
Labels: enhancement

#16 Refactoring and Real Maps
  CMakeLists.txt
  res/PortugalMaps/Aveiro/edges_aveiro.txt
  res/PortugalMaps/Aveiro/nodes_lat_lon_aveiro.txt
  res/PortugalMaps/Aveiro/nodes_x_y_aveiro.txt
  res/PortugalMaps/Braga/edges_braga.txt
  res/PortugalMaps/Braga/nodes_lat_lon_braga.txt
  res/PortugalMaps/Braga/nodes_x_y_braga.txt
  res/PortugalMaps/Coimbra/edges_coimbra.txt
  res/PortugalMaps/Coimbra/nodes_lat_lon_coimbra.txt
  res/PortugalMaps/Coimbra/nodes_x_y_coimbra.txt
  res/PortugalMaps/Ermesinde/edges_ermesinde.txt
  res/PortugalMaps/Ermesinde/nodes_lat_lon_ermesinde.txt
  res/PortugalMaps/Ermesinde/nodes_x_y_ermesinde.txt
  res/PortugalMaps/Fafe/edges_fafe.txt
  res/PortugalMaps/Fafe/nodes_lat_lon_fafe.txt
  res/PortugalMaps/Fafe/nodes_x_y_fafe.txt
  res/PortugalMaps/Gondomar/edges_gondomar.txt
  res/PortugalMaps/Gondomar/nodes_lat_lon_gondomar.txt
  res/PortugalMaps/Gondomar/nodes_x_y_gondomar.txt
  res/PortugalMaps/Lisboa/edges_lisboa.txt
  res/PortugalMaps/Lisboa/nodes_lat_lon_lisboa.txt
  res/PortugalMaps/Lisboa/nodes_x_y_lisboa.txt
  res/PortugalMaps/Maia/edges_maia.txt
  res/PortugalMaps/Maia/nodes_lat_lon_maia.txt
  res/PortugalMaps/Maia/nodes_x_y_maia.txt
  res/PortugalMaps/Porto/edges_porto.txt
  res/PortugalMaps/Porto/nodes_lat_lon_porto.txt
  res/PortugalMaps/Porto/nodes_x_y_porto.txt
  res/PortugalMaps/Viseu/edges_viseu.txt
  res/PortugalMaps/Viseu/nodes_lat_lon_viseu.txt
  res/PortugalMaps/Viseu/nodes_x_y_viseu.txt
  src/Application.cpp
  src/DataImporter.cpp
  src/DataProcessor.cpp
  src/Graph.cpp
  src/include/Application.h
  src/include/DataImporter.h
  src/include/DataProcessor.h
  src/include/Graph.h
  src/meetupRider.cpp
Labels: enhancement, refactoring

#17 New Data
  res/Maps/California/edges_california.txt
  res/Maps/California/nodes_x_y_california.txt
  res/Maps/Ol/edges_ol.txt
  res/Maps/Ol/nodes_x_y_ol.txt
  res/PortugalMaps/Aveiro/edges_aveiro.txt
  res/PortugalMaps/Aveiro/nodes_lat_lon_aveiro.txt
  res/PortugalMaps/Aveiro/nodes_x_y_aveiro.txt
  res/PortugalMaps/Braga/edges_braga.txt
  res/PortugalMaps/Braga/nodes_lat_lon_braga.txt
  res/PortugalMaps/Braga/nodes_x_y_braga.txt
  res/PortugalMaps/Coimbra/edges_coimbra.txt
  res/PortugalMaps/Coimbra/nodes_lat_lon_coimbra.txt
  res/PortugalMaps/Coimbra/nodes_x_y_coimbra.txt
  res/PortugalMaps/Ermesinde/edges_ermesinde.txt
  res/PortugalMaps/Ermesinde/nodes_lat_lon_ermesinde.txt
  res/PortugalMaps/Ermesinde/nodes_x_y_ermesinde.txt
  res/PortugalMaps/Fafe/edges_fafe.txt
  res/PortugalMaps/Fafe/nodes_lat_lon_fafe.txt
  res/PortugalMaps/Fafe/nodes_x_y_fafe.txt
  res/PortugalMaps/Gondomar/edges_gondomar.txt
  res/PortugalMaps/Gondomar/nodes_lat_lon_gondomar.txt
  res/PortugalMaps/Gondomar/nodes_x_y_gondomar.txt
  res/PortugalMaps/Lisboa/edges_lisboa.txt
  res/PortugalMaps/Lisboa/nodes_lat_lon_lisboa.txt
  res/PortugalMaps/Lisboa/nodes_x_y_lisboa.txt
  res/PortugalMaps/Maia/edges_maia.txt
  res/PortugalMaps/Maia/nodes_lat_lon_maia.txt
  res/PortugalMaps/Maia/nodes_x_y_maia.txt
  res/PortugalMaps/Porto/edges_porto.txt
  res/PortugalMaps/Porto/nodes_lat_lon_porto.txt
  res/PortugalMaps/Porto/nodes_x_y_porto.txt
  res/PortugalMaps/Viseu/edges_viseu.txt
  res/PortugalMaps/Viseu/nodes_lat_lon_viseu.txt
  res/PortugalMaps/Viseu/nodes_x_y_viseu.txt
  src/DataImporter.cpp
  src/DataProcessor.cpp
  src/include/DataProcessor.h
  src/meetupRider.cpp
Labels: enhancement

#21 Application Improvements
  src/Application.cpp
  src/DataProcessor.cpp
  src/include/Application.h
  src/meetupRider.cpp
Labels: bug-fix, enhancement

#22 Menus
  CMakeLists.txt
  src/Application.cpp
  src/Menus.cpp
  src/include/Application.h
  src/include/Menus.h
  src/lib/VariadicTable/VariadicTable.h
  src/meetupRider.cpp
Labels: enhancement
